### ISSUE TITLE
How to run trained network on own images?

### ISSUE THREAD

**Issue by cborelc** [davidtvs/PyTorch-ENet#18]
How would I apply the ENet to my own images or videos? I don't see an example in your code. I tried to add images to the test directory and test.txt in VamVid but they were not picked up during testing.

**Comment by davidtvs** [comment]
There is no way to do it from the command line directly, but a function to generate predictions exists [here](https://github.com/davidtvs/PyTorch-ENet/blob/master/main.py#L253). The arguments are the model, images you want to segment, and the mapping from class integers to RGB which is defined in the dataset class.
