### ISSUE TITLE
Resize of Label with categorical classes

### ISSUE THREAD

**Issue by josueortc** [davidtvs/PyTorch-ENet#21]
I was trying to run the code but I found that in the label_transforms you use Resize for training the ENet. How is it possible to use this function when the default transformation is BILINEAR and that would increase the number of categories in the image. For example, if you have number 4 and 6 and resize to a smaller size the image would produce a value of 5 which is actually another category. Am I missing something in terms of the preprocessing of the data?

Thanks for the help.

**Comment by davidtvs** [comment]
You are absolutely right. Thanks for pointing it out. I've pushed this change to master.
