### ISSUE TITLE
How do I save the output file?

### ISSUE THREAD

**Issue by Taeuk-Jang** [davidtvs/PyTorch-ENet#22]
Hi, first of all, thank you for the great work!
I am newcommer for the pytorch and computer vision area,
I trained and tested for the cityscapes ( for testing I used some of validation data to see if it works properly).
I am curious how to save the output file that is segmented. or testing my own photos that don't have annotated data with them?

Thank you again!

**Comment by davidtvs** [comment]
Does #18 answer your question?
