### ISSUE TITLE
Activation selection within the bottlenecks in the network

### ISSUE THREAD

**Issue by heethesh** [davidtvs/PyTorch-ENet#27]
```
if relu:
    activation = nn.ReLU()
else:
    activation = nn.PReLU()
```

Does doing this ensure that PReLU weights are unique for each instance of `activation` within the bottlenecks? While trying to trace this network with `torch.jit`, it gives errors regarding shared weights by `nn.PReLU` layers within the submodules. Perhaps this should be implemented with `copy.deepcopy` for all instances?

To follow the original paper more closely, the number of channels can be specified for each PReLU instance to learn a weight per channel as shown [here](https://pytorch.org/docs/stable/nn.html#prelu).

**Comment by davidtvs** [comment]
honestly, never really used this network much with PReLU activations. How can I replicate your issue?

**Comment by heethesh** [comment]
Was trying to deploy this model to C++ using [this](https://pytorch.org/tutorials/advanced/cpp_export.html) tutorial.

**Comment by davidtvs** [comment]
Fixed the problem causing the error. I still have to update the pre-trained models but in the meantime, the changes are in the [param_sharing_fix](https://github.com/davidtvs/PyTorch-ENet/tree/param_sharing_fix) branch.

Try it out and see if it worts now

**Comment by heethesh** [comment]
@davidtvs Thanks, the tracing works fine now!

**Comment by davidtvs** [comment]
For future reference - the fix is now on the master branch
