### ISSUE TITLE
Test on video

### ISSUE THREAD

**Issue by xxxxxxxiao** [davidtvs/PyTorch-ENet#28]
Hello!
Thank you for your codes. The architecture works great on images. But when I tried to test on videos to implement real-time semantic segmentation the result was unsatisfactory. I used opencv to read and write the video. Do you have any ideas how to solve the issue, or how to get a better result when running the model on videos?
Thanks!

**Comment by davidtvs** [comment]
I think you'll see the most improvement if you fine-tune the network with a dataset that represents the video content better then the pre-trained models
