### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by manganarofabio** [davidtvs/PyTorch-ENet#3]
Hi thanks for sharing your work.
I'm trying to use your network with cityscapes dataset but i get a runtime cuda error during test forwarding (out of memory).
I'm using a gtx 1060 6gb and intel i5 7600. What do you think i can change to make it work properly? Which parameters should i change?

thanks for your help!

**Comment by davidtvs** [comment]
Try to lower the batch size using `-b` or `--batch_size`, or lowering the image resolution using  `--height` and `--width`
