### ISSUE TITLE
Can we pass Single image or a video file to the model to test the semantic Segmentation results.

### ISSUE THREAD

**Issue by prasadpant** [davidtvs/PyTorch-ENet#30]
Once the model is trained can we just pass a single image or inputting video file to the model to test the semantic Segmentation results.

**Comment by davidtvs** [comment]
There's no way to do it from the command-line alone.

You'll have to create a small script to do it. You can reuse the [predict](https://github.com/davidtvs/PyTorch-ENet/blob/master/main.py#L255) function.

**Comment by prasadpant** [comment]
Will create a script and then call it from command-line with the needed parameters, thanks for your input.
