### ISSUE TITLE
RuntimeError: weight tensor should be defined either for all or no classes

### ISSUE THREAD

**Issue by ouening** [davidtvs/PyTorch-ENet#35]
Hi, when I trained my own dataset ( like camvid, has 4 classes), error hapened:
<pre>&gt;&gt;&gt;&gt; [Epoch: 0] Training
Traceback (most recent call last):
  File &quot;main.py&quot;, line 306, in &lt;module&gt;
    model = train(train_loader, val_loader, w_class, class_encoding)
  File &quot;main.py&quot;, line 191, in train
    epoch_loss, (iou, miou) = train.run_epoch(args.print_step)
  File &quot;/media/gaoya/disk/Applications/pytorch/SemanticSegmentation/PyTorch-ENet-master/train.py&quot;, line 47, in run_epoch
    loss = self.criterion(outputs, labels)
  File &quot;/media/gaoya/disk/Applications/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py&quot;, line 547, in __call__
    result = self.forward(*input, **kwargs)
  File &quot;/media/gaoya/disk/Applications/anaconda3/lib/python3.7/site-packages/torch/nn/modules/loss.py&quot;, line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File &quot;/media/gaoya/disk/Applications/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py&quot;, line 1995, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File &quot;/media/gaoya/disk/Applications/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py&quot;, line 1826, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: weight tensor should be defined either for all or no classes at /tmp/pip-req-build-58y_cjjl/aten/src/THCUNN/generic/SpatialClassNLLCriterion.cu:27
</pre>

How can I solve it?

**Comment by davidtvs** [comment]
All I can say from the error is that your call weight tensor doesn't have the expected dimensions. Quoting the pytorch docs: `weight (Tensor, optional) – a manual rescaling weight given to each class. If given, has to be a Tensor of size C`

**Comment by noamzilo** [comment]
same problem for me, for batches whose labels don't have all possible labels. What's the correct way to use weight?

**Comment by davidtvs** [comment]
You should specify the weights of all classes for all batches regardless of which labels are in any specific batch. PyTorch will take the weight corresponding to the class labels that exist itself when computing the loss. See the [NLLLoss docs](https://pytorch.org/docs/stable/generated/torch.nn.NLLLoss.html)

**Comment by ghost** [comment]
if you're a real genius like me, you simply set the wrong number of classes:

```python
class_weights = enet_weighing(train_loader, 3) # whoops - 3 is highest index of a zero-based array, should use 4!
```
