### ISSUE TITLE
what happened to unlabeled or void classes?

### ISSUE THREAD

**Issue by isalirezag** [davidtvs/PyTorch-ENet#36]
Can you please explain how you handle the void classes or unlabeled classes?

I guess more accurately I am asking what is this doing:

    ```parser.add_argument(
        "--with-unlabeled",
        dest='ignore_unlabeled',
        action='store_false',
        help="The unlabeled class is not ignored.")```

are we not ignoring the unlabeled classes? how is that even possible? 
Thank you for explanation in advance!

**Comment by davidtvs** [comment]
You can handle void in two different ways:
- treat the void pixels as their own class, i.e., you want the model to label void pixels as void. In this case, you also care about how good your model is at segmenting void pixels, so your metric includes void pixels.
- ignore void pixels completely, i.e., you don't care what the model says about the void pixels, the model can say that they are a car, building, road, anything. In this case, your metric doesn't include void pixels.

By default, it'll do the first, and `--with-unlabeled` allows you to switch to the second.

**Comment by isalirezag** [comment]
Thank you for explanation!
I think the default version is
