### ISSUE TITLE
Test speed

### ISSUE THREAD

**Issue by InstantWindy** [davidtvs/PyTorch-ENet#4]
Hello ,could you help me how to calculate the segmentation speed.I don't know how to calculate the speed in pytorch. Thank you!

**Comment by davidtvs** [comment]
Using the `time` library and [`torch.cuda.synchronize()`](https://pytorch.org/docs/stable/cuda.html?highlight=synchronize#torch.cuda.synchronize):

```python
import time

torch.cuda.synchronize()
t_start = time.time()

# Image segmentation
predictions = model(images)

torch.cuda.synchronize()
elapsed_time = time.time() - t_start
```

You can adapt the [`predict`](https://github.com/davidtvs/PyTorch-ENet/blob/b4bca4711a96430124e3467da612d30dea5faf17/main.py#L260) function to do this
