### ISSUE TITLE
Training with two classes

### ISSUE THREAD

**Issue by PatrickNa** [davidtvs/PyTorch-ENet#42]
When I try to train the model with only two classes, let's say 'road' and 'unlabeled' the IOU remains 1 all the time. Is there a bug or is it something that I need to configure differently?

**Comment by PatrickNa** [comment]
When I add a third class that as 'unlabeled' represents background the IoU changes over time. However this measure feels like a hack.

**Comment by davidtvs** [comment]
Have you tried using the command line option `--with-unlabeled`?

By default (without that option) the unlabeled class is ignored when computing metrics.

**Comment by PatrickNa** [comment]
This seems to do the trick. Thank you very much!
