### ISSUE TITLE
the question with output

### ISSUE THREAD

**Issue by littlelionly** [davidtvs/PyTorch-ENet#47]
Hellow! when i test the model ,i only got the follow numbers.   How can i get the output results of segmentation?
Numbers:
>>>> Running test dataset
>>>> Avg. loss: 1.0134 | Mean IoU: 0.5271
sky: 0.8987
building: 0.6927
pole: 0.1963
road: 0.9145
pavement: 0.7308
tree: 0.6252
sign_symbol: 0.1862
fence: 0.1774
car: 0.6926
pedestrian: 0.2986
bicyclist: 0.3851
unlabeled: nan

**Comment by davidtvs** [comment]
I think #41 answers your question, please have a look
