### ISSUE TITLE
save all the images

### ISSUE THREAD

**Issue by Robinxin123** [davidtvs/PyTorch-ENet#49]
hello, thanks for your nice work.  
I got a question, how can I  save all the test segmented images, not  the the batch of them. I have checked the function predict and imshow_batch, but don't find the answer.

many thanks

**Comment by davidtvs** [comment]
In the predict function, [here](https://github.com/davidtvs/PyTorch-ENet/blob/master/main.py#L272), you can iterate through the batch of segmented images (the first dimension of the 4D Tensor), convert to numpy and then save them with [`matplotlib.pyplot.savefig`](https://matplotlib.org/3.3.0/api/_as_gen/matplotlib.pyplot.savefig.html).

If it's still not clear, let me know and I'll try to give example code

**Comment by Robinxin123** [comment]
thanks for the reply, I have already solved it.
