### ISSUE TITLE
utils.batch_transform requires some changes

### ISSUE THREAD

**Issue by shirishr** [davidtvs/PyTorch-ENet#5]
When I run python main.py -m test --imshow-batch

I get an error

File "/home/sam/Documents/ComputerVision/PyTorch-ENet/utils.py", line 24, in batch_transform
    return F.stack(transf_slices)
AttributeError: module 'torch.functional' has no attribute 'stack'

**Comment by shirishr** [comment]
**Update:** 

Correction is trivial:

the line should be

return torch.stack(transf_slices)

instead of

return F.stack(transf_slices)

**Comment by shirishr** [comment]
**Update**

Line 22 also should be changed from

transf_slices = [transform(tensor) for tensor in F.unbind(batch)]

to

transf_slices = [transform(tensor) for tensor in **torch**.unbind(batch)]

**Comment by davidtvs** [comment]
I also caught that one when fixing the above.
