### ISSUE TITLE
question about testing the model on an image

### ISSUE THREAD

**Issue by Lee2s** [davidtvs/PyTorch-ENet#53]
Hi, I  have trained the model with my dataset and want to see the segmentation effect of the model.How can I use the model to segment an image?
Thanks in advance.

**Comment by davidtvs** [comment]
Sorry for the late reply. I believe that this is a duplicate issue. Please have a look at my comment in #41.

I'm closing this issue for now, but if you have any follow-up questions feel free to reopen
