### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by CalinTimbusLucian** [davidtvs/PyTorch-ENet#6]
I was wondering what it the solution in case we want to train it on our own dataset?
Thank you in advance.

**Comment by davidtvs** [comment]
Try the following:

1. The first step would be to create the dataloader. You can find examples in [data/camvid.py](https://github.com/davidtvs/PyTorch-ENet/blob/master/data/camvid.py) and [data/cityscapes.py](https://github.com/davidtvs/PyTorch-ENet/blob/master/data/cityscapes.py). An important detail is that two PIL images, the sample image and the target image, must be returned by the `__getitem__` function.
2. Add your dataloader to [data/\_\_init__.py](https://github.com/davidtvs/PyTorch-ENet/blob/master/data/__init__.py).
3. In [args.py](https://github.com/davidtvs/PyTorch-ENet/blob/master/args.py) you should add a new option to the [`--dataset`](https://github.com/davidtvs/PyTorch-ENet/blob/master/args.py#L62) command-line argument. 
4. In [main.py](https://github.com/davidtvs/PyTorch-ENet/blob/master/main.py#L294) you handle that option by importing the dataloader.
5. Run the commands found in the README with your dataset `--dataset YourDatasetName`

**Comment by CalinTimbusLucian** [comment]
Thank you for the prompt response!
Really appreciate it!
