### ISSUE TITLE
mean of empty slice

### ISSUE THREAD

**Issue by yuyangyg** [davidtvs/PyTorch-ENet#8]
Hi thanks for sharing your work.
I'm trying to test your network with cityscapes dataset but i get a mean of empty slice error.
![_006](https://user-images.githubusercontent.com/21524703/46848994-9726a380-ce1f-11e8-8d94-11e7647b8e0a.png)

**Comment by davidtvs** [comment]
The ground-truth labels for the Cityscapes test set are not public. In the test folder you'll see that the labels are all 0 (black) which ends up causing that error because the IoU cannot be computed.

**Comment by yuyangyg** [comment]
Thank you for your prompt reply
