### ISSUE TITLE
Single picture test time

### ISSUE THREAD

**Issue by BobiAce** [davidtvs/PyTorch-ENet#9]
Hi,Thank you for sharing your work.
I train my own data set  and trained 2,456 images of data.  
I found a weird problem when testing with a single image.Different Epoch saved model test times are different in the same CPU test environment. 
Example: Single picture test time,Epoch_50 saves the model takes 0.2s, while Epoch_100 takes 0.9s, and the model size is the same 4.5Mb.
I am looking forward to your reply, thank you.

**Comment by davidtvs** [comment]
Sorry, I somehow missed this until now. I am not sure why that would happen, saving is done through 
`utils.save_checkpoint` which just creates the checkpoint folder if it doesn't exist, uses `torch.save` to save the model, and then saves a small test file with the arguments and some results.

You could try profiling (cProfile and snakeviz) to see exactly what is taking longer
